name: Docker Publish

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - name: Build the Docker image
        run: docker buildx build -f docker/dockerfile --platform linux/amd64 --tag ghcr.io/buildtheearth/uptime-kuma:$(git rev-parse --short HEAD) --tag ghcr.io/buildtheearth/uptime-kuma:latest --target release .
      - name: Docker push tag
        run: docker push ghcr.io/buildtheearth/uptime-kuma:$(git rev-parse --short HEAD)
      - name: Docker push latest
        run: docker push ghcr.io/buildtheearth/uptime-kuma:latest
